[package]
name = "secret"
version = "0.1.0"
authors = [ "Gustav Behm <gustav.behm@iota.org>" ]
edition = "2018"
readme = "README.md"

[dependencies]
thiserror = "1.0"

  [dependencies.stronghold-runtime]
  path = "../../runtime"
  version = "0.2"
  features = [ "stdalloc" ]

  [dependencies.iota-crypto]
  git = "https://github.com/iotaledger/crypto.rs"
  rev = "2dc153079381bf7a87fac54555b26c230a5be593"
  features = [ "random", "chacha", "x25519", "blake2b", "aes" ]

[dev-dependencies.stronghold-test-utils]
path = "../../test_utils"
version = "0.1"
